# Generated by Django 2.0.4 on 2018-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='booked',
            field=models.CharField(choices=[('B', 'Booked'), ('NB', 'Not booked')], default='B', max_length=2),
        ),
    ]
