# Generated by Django 2.0.4 on 2018-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='booked',
            field=models.CharField(choices=[('B', 'Booked'), ('NB', 'Not booked')], default='NB', max_length=2),
        ),
    ]
