# Generated by Django 2.0.4 on 2018-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20180412_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='P', max_length=1),
        ),
    ]
