# Generated by Django 2.0.4 on 2018-04-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20180412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cost_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
