# Generated by Django 2.0.4 on 2018-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20180412_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehicle_image'),
        ),
    ]
