# Generated by Django 2.0.4 on 2018-04-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('startDate', models.DateTimeField(verbose_name='Start date ')),
                ('endDate', models.DateTimeField(verbose_name='end date ')),
                ('securityDeposit', models.IntegerField()),
                ('status', models.CharField(choices=[('B', 'booked'), ('NB', 'not booked')], default='NB', max_length=2)),
                ('discountId', models.CharField(max_length=100)),
                ('allottedUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
