# Generated by Django 2.0.4 on 2018-04-15 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '__first__'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('source_latitude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('source_longitude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('destination_latitude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('destination_longitude', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('startDate', models.DateTimeField(verbose_name='Start date ')),
                ('endDate', models.DateTimeField(verbose_name='end date ')),
                ('securityDeposit', models.IntegerField()),
                ('status', models.CharField(choices=[('B', 'booked'), ('NB', 'not booked'), ('E', 'expired')], default='NB', max_length=2)),
                ('discountId', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('allottedDriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('allottedUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
