# Generated by Django 2.0.4 on 2018-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ride',
            new_name='vehicle',
        ),
    ]
