# Generated by Django 2.0.2 on 2018-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('B', 'booked'), ('NB', 'not booked'), ('E', 'expired')], default='NB', max_length=2),
        ),
    ]
