# Generated by Django 2.0.4 on 2018-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180411_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='latitude',
            new_name='destination_latitude',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='longitude',
            new_name='destination_longitude',
        ),
        migrations.AddField(
            model_name='book',
            name='source_latitude',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='book',
            name='source_longitude',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
