# Generated by Django 2.0.4 on 2018-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180411_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
