# Generated by Django 2.0.4 on 2018-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180411_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
