# Generated by Django 2.0.4 on 2018-04-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20180412_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.FloatField(),
        ),
    ]
